### ISSUE TITLE
image.png issue

### ISSUE THREAD

**Issue by danielordogh94** [danielordogh94/TGN-RFT-zh2#1]
Norbi, ne image.png-ként töltsd fel a feladatot, hanem lehetőleg "Class diagram" néven.

**Comment by NBence99** [comment]
Véletlen hiba volt szerintem

**Comment by klnorbert** [comment]
Jólvan na átírom a kedvedért.
![class diagram](https://user-images.githubusercontent.com/74738259/100895621-107d2680-34be-11eb-935e-6daf75df9af1.png)

**Comment by danielordogh94** [comment]
Köszi, így jó!
